---
# tasks file for common

- name: use apt-cacher for fast package updates
  copy: src=01proxy dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: set system timezone
  copy: content='America/Sao_Paulo' dest=/etc/timezone owner=root group=root mode=0644
  notify: update timezone

- name: generate pt_BR.UTF-8 locales
  locale_gen: name=pt_BR.UTF-8 state=present

- name: set pt_BR.UTF-8 locales as default
  debconf: name=locales question='locales/default_environment_locale' value=pt_BR.UTF-8 vtype='select'

- name: upgrade all system packages
  apt: upgrade=dist

- name: install packages
  apt: name={{ item }} state=present autoremove=yes
  with_items:
    - ntp
    - vim
    - libpam-systemd

- name: set default system editor
  alternatives: name=editor path=/usr/bin/vim.basic

- name: change /etc/vim/vimrc file
  copy: src=vimrc dest=/etc/vim/vimrc owner=root group=root mode=0644

- name: change /etc/bash.bashrc file
  copy: src=bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644

- name: change .bashrc file for user root
  copy: src=.bashrc.root dest=/root/.bashrc owner=root group=root mode=0644

- name: change .bashrc file for user vagrant
  copy: src=.bashrc.vagrant dest=/home/vagrant/.bashrc owner=vagrant group=vagrant mode=0644
