---
# tasks file for wordpress

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - apache2
  - ca-certificates
  - libapache2-mod-php
  - libjs-cropper
  - libjs-mediaelement
  - libphp-phpmailer
  - mysql-client
  - php-gd
  - php-getid3
  - php-mysql

- name: enables the apache2 module rewrite
  apache2_module: name=rewrite state=present

- name: create wordpress group
  group: name={{ WORDPRESS_GROUP }} state=present

- name: create wordpress user
  user: name={{ WORDPRESS_USER }} comment="Wordpress Application User account" group={{ WORDPRESS_GROUP }} shell=/bin/bash home=/var/www/{{ WORDPRESS_HOME }}

- name: download latest wordpress
  unarchive: src="https://wordpress.org/latest.tar.gz" dest=/var/www/{{ WORDPRESS_HOME }} remote_src=yes owner={{ WORDPRESS_USER }} group={{ WORDPRESS_GROUP }}

- name: create .htaccess file
  copy: src=.htaccess dest=/var/www/{{ WORDPRESS_HOME }}/wordpress/.htaccess mode=0664 owner={{ WORDPRESS_USER }} group=www-data

- name: fetch random salts for WordPress config
  uri: url=https://api.wordpress.org/secret-key/1.1/salt/ return_content=yes
  register: wp_salt

- name: create wp-config.php file
  template: src=wp-config.php.j2 dest=/var/www/{{ WORDPRESS_HOME }}/wordpress/wp-config.php mode=0644 owner={{ WORDPRESS_USER }} group={{ WORDPRESS_GROUP }}

- name: change wp-content group ownership and access
  file: path=/var/www/{{ WORDPRESS_HOME }}/wordpress/wp-content group=www-data mode=0775

- name: change wp-content/themes group ownership and access
  file: path=/var/www/{{ WORDPRESS_HOME }}/wordpress/wp-content/themes group=www-data mode=0775 recurse=yes

- name: create blog.vagrant.local.conf apache configuration file
  template: src=blog.vagrant.local.conf.j2 dest=/etc/apache2/sites-available/blog.vagrant.local.conf mode=0644 owner=root group=root
  notify:
    - enable blog.vagrant.local configuration under apache
    - restart apache
