---
# This playbook deploys the whole application stack in this site.

- name: install python-minimal (python 2) if not installed
  hosts: all
  gather_facts: False
  become: True

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt update -y && apt install python-minimal -y)

- name: apply common configuration to all nodes
  hosts: all
  become: True
  roles:
  - common

- name: apply mysql configuration to database nodes
  hosts: database
  become: True
  roles:
  - mysql

- name: apply apache configuration to web nodes
  hosts: web
  become: True
  roles:
  - wordpress
