---
# tasks file for java

- name: append exclusion from apt-cacher-ng when downloading from download.oracle.com
  lineinfile: dest=/etc/apt/apt.conf.d/01proxy line='Acquire::http::Proxy { download.oracle.com DIRECT; };'

- name: add apt repository webupd8team java
  apt_repository: repo='ppa:webupd8team/java'

- name: set yes to oracle license
  debconf: name='oracle-java{{ java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install java package
  apt: name=oracle-java{{ java_version }}-installer state=present
