---
# tasks file for redis-master

- name: install packages
  apt: name={{ item }} state=present autoremove=yes
  with_items:
    - redis-server
    - redis-tools

- name: set redis master configuration
  copy: src=redis.conf dest=/etc/redis/redis.conf owner=root group=root mode=0644
  notify: restart redis-server
