---
# tasks file for predictionio

- name: install jdk package
  apt: name={{ item }} state=present
  with_items:
  - openjdk-8-jdk-headless

- name: set JAVA_HOME under /etc/environment
  lineinfile: path=/etc/environment regexp='^export JAVA_HOME=' line='export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'

- name: add group predictionio
  group: name=predictionio

- name: add user predictionio
  user: name=predictionio comment='PredictionIO User Account' createhome=yes group=predictionio shell=/bin/bash state=present

- name: create /opt/predictionio/apache-predictionio directory
  file: path=/opt/predictionio/apache-predictionio state=directory owner=predictionio group=predictionio mode=0755

- name: install Apache PredictionIO from web mirror
  unarchive: remote_src=yes src=http://ftp.unicamp.br/pub/apache/incubator/predictionio/0.12.0-incubating/apache-predictionio-0.12.0-incubating.tar.gz dest=/opt/predictionio/apache-predictionio owner=predictionio group=predictionio creates=/opt/predictionio/LICENSE.txt

- name: execute make-distribution.sh
  shell: ./make-distribution.sh > make-distribution.log 2>&1
  args:
    chdir: /opt/predictionio/apache-predictionio/
    creates: PredictionIO-0.12.0-incubating.tar.gz
  become: true
  become_user: predictionio

- name: extract PredictionIO-0.12.0-incubating.tar.gz
  unarchive: copy=no src=/opt/predictionio/apache-predictionio/PredictionIO-0.12.0-incubating.tar.gz dest=/opt/predictionio owner=predictionio group=predictionio creates=/opt/predictionio/PredictionIO-0.12.0-incubating/LICENSE.txt

- name: create /opt/predictionio/PredictionIO-0.12.0-incubating/vendors directory
  file: path=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors state=directory owner=predictionio group=predictionio mode=0755

- name: install Apache Spark from web
  unarchive: remote_src=yes src=http://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.6.tgz dest=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors owner=predictionio group=predictionio creates=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors/spark-2.1.1-bin-hadoop2.6/LICENSE.txt

- name: install Elasticsearch from web
  unarchive: remote_src=yes src=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.2.tar.gz dest=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors owner=predictionio group=predictionio creates=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors/elasticsearch-5.5.2/LICENSE.txt

- name: install Apache HBase from web
  unarchive: remote_src=yes src=http://www-eu.apache.org/dist/hbase/1.2.6/hbase-1.2.6-bin.tar.gz dest=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors owner=predictionio group=predictionio creates=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors/hbase-1.2.6/LICENSE.txt

- name: set /opt/predictionio/PredictionIO-0.12.0-incubating/vendors/hbase-1.2.6/conf/hbase-site.xml
  copy: src=hbase-site.xml dest=/opt/predictionio/PredictionIO-0.12.0-incubating/vendors/hbase-1.2.6/conf/hbase-site.xml owner=predictionio group=predictionio mode=0644 backup=yes

- name: set /opt/predictionio/PredictionIO-0.12.0-incubating/conf/pio-env.sh
  copy: src=pio-env.sh dest=/opt/predictionio/PredictionIO-0.12.0-incubating/conf/pio-env.sh owner=predictionio group=predictionio mode=0644 backup=yes

- name: set /opt/predictionio/PredictionIO-0.12.0-incubating/bin under PATH for predictionio user
  lineinfile: path=/home/predictionio/.bashrc regexp='PATH=' line='PATH=$PATH:/opt/predictionio/PredictionIO-0.12.0-incubating/bin; export PATH'
